export const MOCK_USERS = [
    {
        id: 22102001,
        stt: 1,
        username: 'tranthilan',
        password: '123456',
        fullName: 'Trần Thị Lan',
        gender: 'Nữ',
        email: 'lan.tran@gmail.com',
        phone: '0905123456',
        role: 'Giáo viên',
        status: 'Kích hoạt',
    },
    {
        id: 22102002,
        stt: 2,
        username: 'nguyenvanbao',
        password: '123456',
        fullName: 'Nguyễn Văn Bảo',
        gender: 'Nam',
        email: 'bao.nguyen@gmail.com',
        phone: '0912345678',
        role: 'Ban giám hiệu',
        status: 'Kích hoạt',
    },
    {
        id: 22102003,
        stt: 3,
        username: 'phamthithao',
        password: '123456',
        fullName: 'Phạm Thị Thảo',
        gender: 'Nữ',
        email: 'thao.pham@gmail.com',
        phone: '0933456789',
        role: 'Phụ huynh',
        status: 'Vô hiệu hóa',
    },
    {
        id: 22102004,
        stt: 4,
        username: 'lengochoang',
        password: '123456',
        fullName: 'Lê Ngọc Hoàng',
        gender: 'Nam',
        email: 'hoang.le@gmail.com',
        phone: '0977123456',
        role: 'Kế toán',
        status: 'Kích hoạt',
    },
    {
        id: 22102005,
        stt: 5,
        username: 'dangkimphung',
        password: '123456',
        fullName: 'Đặng Kim Phụng',
        gender: 'Nữ',
        email: 'phung.dang@gmail.com',
        phone: '0905789641',
        role: 'Giáo viên',
        status: 'Kích hoạt',
    },
    {
        id: 22102006,
        stt: 6,
        username: 'trongminhduc',
        password: '123456',
        fullName: 'Trọng Minh Đức',
        gender: 'Nam',
        email: 'duc.trong@gmail.com',
        phone: '0912349987',
        role: 'Ban giám hiệu',
        status: 'Kích hoạt',
    },
    {
        id: 22102007,
        stt: 7,
        username: 'ngochoamai',
        password: '123456',
        fullName: 'Ngô Châu Mai',
        gender: 'Nữ',
        email: 'mai.ngo@gmail.com',
        phone: '0938897654',
        role: 'Giáo viên',
        status: 'Kích hoạt',
    },
    {
        id: 22102008,
        stt: 8,
        username: 'phamthanhhai',
        password: '123456',
        fullName: 'Phạm Thành Hải',
        gender: 'Nam',
        email: 'hai.pham@gmail.com',
        phone: '0985456732',
        role: 'Phụ huynh',
        status: 'Kích hoạt',
    },
    {
        id: 22102009,
        stt: 9,
        username: 'buithithuy',
        password: '123456',
        fullName: 'Bùi Thị Thùy',
        gender: 'Nữ',
        email: 'thuy.bui@gmail.com',
        phone: '0967345211',
        role: 'Tổ trưởng',
        status: 'Kích hoạt',
    },
    {
        id: 22102010,
        stt: 10,
        username: 'hohuuhieu',
        password: '123456',
        fullName: 'Hồ Hữu Hiếu',
        gender: 'Nam',
        email: 'hieu.ho@gmail.com',
        phone: '0903458923',
        role: 'Phụ huynh',
        status: 'Vô hiệu hóa',
    },
    {
        id: 22102011,
        stt: 11,
        username: 'dangthiminh',
        password: '123456',
        fullName: 'Đặng Thị Minh',
        gender: 'Nữ',
        email: 'minh.dang@gmail.com',
        phone: '0912938465',
        role: 'Giáo viên',
        status: 'Kích hoạt',
    },
    {
        id: 22102012,
        stt: 12,
        username: 'trankhanhduy',
        password: '123456',
        fullName: 'Trần Khánh Duy',
        gender: 'Nam',
        email: 'duy.tran@gmail.com',
        phone: '0945786245',
        role: 'Giáo viên',
        status: 'Kích hoạt',
    },
    {
        id: 22102013,
        stt: 13,
        username: 'huynhthiha',
        password: '123456',
        fullName: 'Huỳnh Thị Hà',
        gender: 'Nữ',
        email: 'ha.huynh@gmail.com',
        phone: '0975632184',
        role: 'Kế toán',
        status: 'Kích hoạt',
    },
    {
        id: 22102014,
        stt: 14,
        username: 'vothanhtung',
        password: '123456',
        fullName: 'Võ Thành Tùng',
        gender: 'Nam',
        email: 'tung.vo@gmail.com',
        phone: '0934561278',
        role: 'Phụ huynh',
        status: 'Kích hoạt',
    },
    {
        id: 22102015,
        stt: 15,
        username: 'vuthuha',
        password: '123456',
        fullName: 'Vũ Thu Hà',
        gender: 'Nữ',
        email: 'ha.vu@gmail.com',
        phone: '0956321487',
        role: 'Giáo viên',
        status: 'Vô hiệu hóa',
    },
    {
        id: 22102016,
        stt: 16,
        username: 'lamhoangnam',
        password: '123456',
        fullName: 'Lâm Hoàng Nam',
        gender: 'Nam',
        email: 'nam.lam@gmail.com',
        phone: '0945123687',
        role: 'Tổ trưởng',
        status: 'Kích hoạt',
    },
];
